export const clinics = [
  {
    id: 1,
    name: "Clinic",
    specialty: "psixoloq",
    clinic: "Mehlem",
    rate: 4.5,
    rate_limit: 29,
    option: ["Temiz", "Uygun", "Lab"],
    address: "Heydər Əliyev Prospekti 21",
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 2,
    name: "Clinic",
    specialty: "psixoloq",
    rate: 4.5,
    rate_limit: 29,
    clinic: "Mehlem",
    address: "Heydər Əliyev Prospekti 21",
    option: ["Temiz", "Uygun", "Lab"],
    availability: "Busy",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 3,
    name: "Clinic",
    specialty: "psixoloq",
    rate: 4.5,
    rate_limit: 29,
    clinic: "Mehlem",
    option: ["Temiz", "Uygun", "Lab"],
    address: "Heydər Əliyev Prospekti 21",
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 4,
    name: "Clinic",
    rate: 4.5,
    rate_limit: 29,
    specialty: "psixoloq",
    option: ["Temiz", "Uygun", "Lab"],
    address: "Heydər Əliyev Prospekti 21",
    clinic: "Mehlem",
    availability: "Busy",
    image: "https://via.placeholder.com/100",
  },
];
