export const doctors = [
  {
    id: 1,
    name: "Dr. John Doe",
    specialty: "psixoloq",
    clinic: "Mehlem",
    rate: 4.5,
    rate_limit: 29,
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 2,
    name: "Dr. John Doe",
    specialty: "psixoloq",
    clinic: "Mehlem",
    rate: 4.5,
    rate_limit: 29,
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 3,
    name: "Dr. John Doe",
    specialty: "psixoloq",
    clinic: "Mehlem",
    rate: 4.5,
    rate_limit: 29,
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 4,
    name: "Dr. John Doe",
    specialty: "psixoloq",
    clinic: "Mehlem",
    rate: 4.5,
    rate_limit: 29,
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 5,
    name: "Dr. Sarah Lee",
    specialty: "psixoloq",
    rate: 4.5,
    rate_limit: 29,
    clinic: "Mehlem",
    halfStar: true,
    availability: "Busy",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 6,
    name: "Dr. Emily Clark",
    specialty: "psixoloq",
    rate: 4.5,
    rate_limit: 29,
    clinic: "Mehlem",
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 7,
    name: "Dr. Emily Clark",
    specialty: "psixoloq",
    rate: 4.5,
    rate_limit: 29,
    clinic: "Mehlem",
    halfStar: true,
    availability: "Available",
    image: "https://via.placeholder.com/100",
  },
  {
    id: 8,
    name: "Dr. Michael Brown",
    rate: 4.5,
    rate_limit: 29,
    specialty: "psixoloq",
    halfStar: true,
    clinic: "Mehlem",
    availability: "Busy",
    image: "https://via.placeholder.com/100",
  },
];
